# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=20)),
                ('phone_s', models.CharField(max_length=20)),
                ('gender_s', models.CharField(max_length=2)),
                ('gender_t', models.CharField(max_length=2)),
                ('address_s', models.CharField(max_length=30)),
                ('description_s', models.TextField(default='無')),
                ('class_week', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('other', models.TextField(default='無')),
            ],
        ),
    ]
